language: cpp
os: linux
compiler: gcc
sudo: required
dist: xenial

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.11.2-xenial
  - sudo apt-get -qq update

install:
  - sudo apt-get --yes install qt511base qt511serialport

before_script:
  - source /opt/qt511/bin/qt511-env.sh
  - qmake SmartHHC.pro -spec linux-g++ CONFIG+=debug

script:
  - make
