language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      osx_image: xcode9.4

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq                                     ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                                                   ; fi

install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install libgl1-mesa-dev qt510base qt510serialport ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt*/bin/qt*-env.sh                                    ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5                                                    ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force qt5                                               ; fi

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then qmake SmartHHC.pro -spec linux-g++ CONFIG+=release PREFIX=/usr ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -j$(nproc)                                                ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make INSTALL_ROOT=SmartHHC install                             ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then qmake SmartHHC.pro -spec macx-xcode CONFIG+=release              ; fi

after_success:
- chmod +x ./deploy/travis.sh
- source ./deploy/travis.sh

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: EgJEc+oJls74TNu1g3KG1BCBnwr5Vyrfk5lG7cy2SiMlztFaVQmRistgAWdWnsWI3umH/Yr4ySLtD8DDFZoUUtLEshGfyZkxI0vF8pFnalBEpVxqHIf8oiZKA0KtK0Az4jk3INftgHz6ItgsXoSlG3eFovWQ3xsdQIFPWLbM6D3Mtmw9sQIrzmdRyOwv63Z+knr2ENK7jsXorbJ6Patekg3WmqHNOclzBJqbWyEyCNwkB86vrfhT7mL+v0/OdCu8cNPfhiCxwaJpTxUxeibXxUFZwzTb8AZdIpAZ7Oc2gPlXYPg01h5Bp30zHduZWvOt98zSKiXw6Cc7zlgFAyWzNDjdW80WbqmAP50DsPYWPnsrKPOoTGfwym8IwX+QsmoqXxxDlNNgqWLoeAySWVNUEGe+N8YftpbxUNQ3xz5i9mG8nN+fQHtl+wLtnJOFKdeXeQH6Ho6xKA3j9Tyo7RypUgfiWFv2QWXRcVy3nMIuMQKcFSZ7SzfVi4Z9oBB+PDtSGxNCwlOzF18p/MV9MRHgFF5cvYfZDEdifTyEukQkUf3dm4vATrEiRpUH9jZ9IXXuXYFpnMutxJCRnfkkzFfpzE/lpBjo1AlSJ8Sh3JHvAE4p3oGSaLGlnpQEeV0/q8SzTZWrjaHX1D1ELRVNa1xNTtI0DzOB6cBHdxp5XlbJhuc=
  file: $DEPLOYFILE
  on:
    repo: azdrums/smarthhc
    tags: true
